### ISSUE TITLE
https where available

### ISSUE THREAD

**Issue by jtrim** [cacheflowe/embetter#3]
Looks like at least Vimeo supports https for [this particular API call](https://github.com/cacheflowe/embetter/blob/master/embetter.js#L201). Can you think of any reason not to default these service calls to https where it's available?

**Comment by cacheflowe** [comment]
@jtrim Cool with me, but just an FYI - your project doesn't actually use embetter.js to make API calls. But thanks for the update :smile:

**Comment by jtrim** [comment]
It actually is being used in our app - which is what initiated the submitting of this PR. Maybe we should chat about it offline?
